/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const GalleryIndexLazyImport = createFileRoute('/gallery/')()
const GalleryItemGalleryItemIdLazyImport = createFileRoute(
  '/gallery/item/$galleryItemId',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GalleryIndexLazyRoute = GalleryIndexLazyImport.update({
  path: '/gallery/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/gallery.index.lazy').then((d) => d.Route))

const GalleryItemGalleryItemIdLazyRoute =
  GalleryItemGalleryItemIdLazyImport.update({
    path: '/gallery/item/$galleryItemId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/gallery.item.$galleryItemId.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/gallery/item/$galleryItemId': {
      id: '/gallery/item/$galleryItemId'
      path: '/gallery/item/$galleryItemId'
      fullPath: '/gallery/item/$galleryItemId'
      preLoaderRoute: typeof GalleryItemGalleryItemIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
  GalleryIndexLazyRoute,
  GalleryItemGalleryItemIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/gallery/",
        "/gallery/item/$galleryItemId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/gallery/": {
      "filePath": "gallery.index.lazy.tsx"
    },
    "/gallery/item/$galleryItemId": {
      "filePath": "gallery.item.$galleryItemId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
